// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR20__B47c6St3scCy8CkehAZrJ3ubBXo',
    appId: '1:406030308933:android:bf288ba622e8d81e1af52c',
    messagingSenderId: '406030308933',
    projectId: 'spacex-flutter-auth',
    storageBucket: 'spacex-flutter-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6kJuhVNuSQ4g2KWBCmRaeJJRrimCgjk',
    appId: '1:406030308933:ios:09b839451252d9e01af52c',
    messagingSenderId: '406030308933',
    projectId: 'spacex-flutter-auth',
    storageBucket: 'spacex-flutter-auth.appspot.com',
    androidClientId: '406030308933-o23272sj05jr2nu445uu3tllu2fahs1q.apps.googleusercontent.com',
    iosClientId: '406030308933-iqaadfqjti56dfjrqn6v7vln2dvenpda.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacex',
  );

}